import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  scrollView: {
    flex: 1,
  },
  imageUploadContainer: {
    alignItems: "center",
    padding: 16,
  },
  productImage: {
    width: 200,
    height: 200,
    borderRadius: 12,
  },
  placeholderImage: {
    width: 200,
    height: 200,
    borderRadius: 12,
    backgroundColor: "#F5F5F5",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#6B9774",
    borderStyle: "dashed",
  },
  imageButtons: {
    flexDirection: "row",
    marginTop: 16,
    gap: 16,
  },
  imageButton: {
    justifyContent: "center",
    backgroundColor: "#FAF3EB",
    alignItems: "center",
    height: 50,
    width: 50,
    borderWidth: 0.5,
    borderColor: "#0D3A2D",
    borderRadius: 16,
    shadowColor: "#0D3A2D",
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.25,
    shadowRadius: 2,
    elevation: 3,
  },
  productInfoContainer: {
    backgroundColor: "#fff",
    borderRadius: 8,
    padding: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
    marginHorizontal: 16,
    marginTop: 16,
  },
  pricingSectionContainer: {
    marginHorizontal: 16,
    marginTop: 16,
  },
  ingredientsSectionContainer: {
    backgroundColor: "#fff",
    borderRadius: 8,
    padding: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
    margin: 16,
  },
  productNameInput: {
    fontSize: 14,
    fontWeight: "semibold",
    color: "#171725",
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#E0E0E0",
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: "#F5F5F5",
  },
  pricingContainer: {
    backgroundColor: "#fff",
    borderRadius: 8,
    padding: 16,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#E0E0E0",
  },
  pricingInputWrapper: {
    marginBottom: 4,
  },
  priceContainer: {
    marginBottom: 0,
  },
  priceInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F5F5F5",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 2,
    borderWidth: 1,
    borderColor: "#E0E0E0",
  },
  inputLabel: {
    fontSize: 16,
    color: "#181D27",
    marginBottom: 8,
    fontWeight: "500",
  },
  priceInput: {
    fontSize: 16,
    color: "#000",
    flex: 1,
  },
  currencySymbol: {
    fontSize: 16,
    color: "#B36718",
    marginRight: 8,
    fontWeight: "500",
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "semi-bold",
    color: "#181D27",
    marginBottom: 16,
  },
  ingredientGroup: {
    marginBottom: 24,
    position: "relative",
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 16,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  ingredientColumn: {
    gap: 16,
  },
  pickerContainer: {
    borderWidth: 1,
    borderColor: "#181D27",
    borderRadius: 8,
    overflow: "hidden",
    padding: 12,
    backgroundColor: "#F5F5F5",
  },
  pickerLabel: {
    fontSize: 14,
    color: "#181D27",
    marginBottom: 8,
  },
  picker: {
    height: 53,
    marginTop: -8,
    color: "#181D27",
  },
  quantityContainer: {
    borderWidth: 1,
    borderColor: "#181D27",
    borderRadius: 8,
    padding: 12,
    backgroundColor: "#F5F5F5",
  },
  quantityInput: {
    height: 40,
    fontSize: 16,
    color: "#0D3A2D",
  },
  removeButton: {
    position: "absolute",
    right: -8,
    top: -8,
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 4,
  },
  addMoreButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 12,
    borderWidth: 1,
    borderColor: "#0D3A2D",
    borderRadius: 8,
    marginTop: 8,
    backgroundColor: "#F5F5F5",
  },
  addMoreText: {
    color: "#0D3A2D",
    fontSize: 16,
    marginLeft: 8,
  },
  buttonContainer: {
    padding: 16,
    backgroundColor: "#fff",
    borderTopWidth: 1,
    borderTopColor: "#E0E0E0",
    marginBottom: 32,
  },
  addProductButton: {
    backgroundColor: "#6B9774",
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
    height: 50,
  },
  addProductButtonText: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "bold",
  },
  quantityInputError: {
    borderColor: "#ff0000",
    borderWidth: 1,
  },
  errorText: {
    color: "#ff0000",
    fontSize: 12,
    marginTop: 4,
  },
  descriptionInput: {
    height: 80,
    textAlignVertical: "top",
    marginBottom: 16,
    fontSize: 16,
    fontWeight: "semi-bold",
    color: "#0D3A2D",
    borderWidth: 1,
    borderColor: "#E0E0E0",
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: "#F5F5F5",
  },
});

export default styles; 