import { StyleSheet, Platform } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  notificationButton: {
    position: "relative",
    marginTop: 16,
  },
  badge: {
    position: "absolute",
    top: -5,
    right: -5,
    backgroundColor: "red",
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 4,
  },
  badgeText: {
    color: "white",
    fontSize: 12,
    fontWeight: "bold",
  },
  headerButtons: {
    flexDirection: "row",
    gap: 10,
    marginTop: 16,
  },
  headerButton: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    alignContent: "center",
    justifyContent: "center",
    backgroundColor: "#6B9774",
  },
  activeButton: {
    backgroundColor: "#8B4513",
  },
  headerButtonText: {
    color: "#fff",
    fontWeight: "600",
  },
  productList: {
    padding: 4,
    justifyContent: "space-between",
  },
  productListWithReview: {
    paddingBottom: 180,
  },
  card: {
    width: "31.5%",
    margin: "0.5%",
    borderRadius: 8,
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  imageContainer: {
    height: 85,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    overflow: "hidden",
  },
  productImage: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  cardFooter: {
    backgroundColor: "#0D3A2D",
    padding: 8,
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
    minHeight: 35,
  },
  productTitle: {
    color: "white",
    fontSize: 11,
    fontWeight: "bold",
    marginBottom: 2,
    height: 24,
  },
  productPrice: {
    color: "#FFBB03",
    fontSize: 12,
    fontWeight: "bold",
    marginBottom: 2,
  },
  quantityContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#0D3A2D",
    paddingHorizontal: 4,
    paddingVertical: 2,
    borderRadius: 4,
    marginTop: 2,
  },
  quantityLabel: {
    color: "white",
    fontSize: 9,
  },
  quantityValueContainer: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: "transparent",
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 4,
  },
  quantityValueContainerActive: {
    backgroundColor: "#FFBB03",
    borderRadius: 10,
  },
  quantityValue: {
    color: "white",
    fontSize: 10,
    fontWeight: "bold",
  },
  quantityValueActive: {
    color: "black",
  },
  reviewContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "white",
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: "#eee",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: -2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 5,
  },
  totalPanel: {
    backgroundColor: "#0D3A2D",
    padding: 16,
    borderRadius: 12,
    alignItems: "stretch",
  },
  reviewButtonInPanel: {
    backgroundColor: "#FFBB03",
    borderRadius: 8,
    paddingVertical: 12,
    marginBottom: 12,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 2,
    elevation: 2,
  },
  reviewButtonTextInPanel: {
    color: "#0D3A2D",
    fontSize: 16,
    fontWeight: "bold",
    letterSpacing: 1,
  },
  totalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  totalLabel: {
    fontSize: 14,
    color: "#fff",
  },
  totalValue: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#FFBB03",
  },
  emptyContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  emptyText: {
    fontSize: 16,
    color: "#666",
    textAlign: "center",
  },
  businessName: {
    marginLeft: 16,
    fontSize: 16,
    fontWeight: "bold",
    marginTop: 16,
    color: "#222",
    letterSpacing: 1.2,
    fontFamily:
      Platform.OS === "ios" ? "AvenirNext-DemiBold" : "sans-serif-medium",
    textShadowColor: "rgba(107, 151, 116, 0.15)",
    textShadowOffset: { width: 1, height: 2 },
    textShadowRadius: 2,
  },
});

export default styles; 