import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  searchContainer: {
    padding: 16,
    paddingTop: 8,
    paddingBottom: 16,
  },
  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F5F5F5",
    borderRadius: 32,
    paddingHorizontal: 16,
    height: 45,
    shadowColor: "#000",
    shadowOffset: {
      width: 5,
      height: 5,
    },
    shadowOpacity: 0.1,
    borderWidth: 1,
    borderColor: "#6B9774",
    backgroundColor: "#F5F5F5",
    shadowColor: "#000",
    shadowOffset: {
      width: -3,
      height: -3,
    },
  },
  searchInput: {
    flex: 1,
    marginLeft: 8,
    color: "#0D3A2D",
    fontSize: 16,
    fontWeight: "500",
  },
  clearButton: {
    padding: 4,
    marginLeft: 8,
  },
  contentContainer: {
    flex: 1,
    backgroundColor: "white",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: -2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 5,
  },
  productList: {
    padding: 8,
    justifyContent: "space-between",
  },
  card: {
    width: "48%",
    margin: "1%",
    borderRadius: 12,
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  imageContainer: {
    height: 105,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    overflow: "hidden",
  },
  productImage: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  cardFooter: {
    backgroundColor: "#0D3A2D",
    padding: 16,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    minHeight: 65,
  },
  productTitle: {
    color: "white",
    fontSize: 14,
    fontWeight: "bold",
    marginBottom: 4,
  },
  productPrice: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
  },
  emptyContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  emptyText: {
    fontSize: 16,
    color: "#666",
    textAlign: "center",
  },
  productDescription: {
    color: "rgba(255, 255, 255, 0.8)",
    fontSize: 12,
    marginTop: 4,
  },
  deleteButton: {
    position: "absolute",
    top: 8,
    right: 8,
    backgroundColor: "rgba(255, 0, 0, 0.7)",
    borderRadius: 15,
    width: 30,
    height: 30,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  // Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContainer: {
    backgroundColor: "#fff",
    borderRadius: 20,
    width: "90%",
    maxHeight: "85%",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 10,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#E0E0E0",
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#0D3A2D",
  },
  closeButton: {
    padding: 4,
  },
  modalContent: {
    padding: 16,
  },
  modalImageContainer: {
    alignItems: "center",
    marginBottom: 16,
  },
  modalProductImage: {
    width: 125,
    height: 100,
    borderRadius: 8,
    resizeMode: "cover",
  },
  modalInfoSection: {
    marginBottom: 20,
  },
  modalProductName: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#0D3A2D",
    marginBottom: 8,
    textAlign: "center",
  },
  modalProductDescription: {
    fontSize: 14,
    color: "#666",
    textAlign: "center",
    lineHeight: 22,
  },
  modalPricingSection: {
    backgroundColor: "#F8F9FA",
    borderRadius: 12,
    padding: 16,
    marginBottom: 8,
  },
  modalPriceRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  modalPriceLabel: {
    fontSize: 14,
    color: "#666",
    fontWeight: "500",
  },
  modalPriceValue: {
    fontSize: 14,
    color: "#0D3A2D",
    fontWeight: "bold",
  },
  modalIngredientsSection: {
    backgroundColor: "#F8F9FA",
    borderRadius: 12,
    padding: 16,
    marginBottom: 4,
  },
  modalSectionTitle: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#0D3A2D",
    marginBottom: 8,
  },
  modalIngredientItem: {
    backgroundColor: "#fff",
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  modalIngredientInfo: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  modalIngredientName: {
    fontSize: 14,
    color: "#0D3A2D",
    fontWeight: "500",
    flex: 1,
  },
  modalIngredientQuantity: {
    fontSize: 14,
    color: "#B36718",
    fontWeight: "bold",
  },
  modalDateSection: {
    padding: 16,
    marginBottom: 8,
    flexDirection: "row",
    justifyContent: "flex-end",
  },
  modalDateLabel: {
    fontSize: 12,
    color: "#666",
    fontWeight: "500",
    marginRight: 8,
  },
  modalDateValue: {
    fontSize: 12,
    color: "#0D3A2D",
    fontWeight: "500",
  },
});

export default styles; 